
name: generate-build-publish

on:
  workflow_dispatch:
    #
  push:
    branches:
      - 'master'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Action Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Read MCDR version
        run: |
          ls -al
          read v <'.MCDR_version_cache.txt'
          [ -n "$v" ] || v='2'
          echo "MCDR_VERSION=$v" >> $GITHUB_ENV
      -
        name: Generate Dockerfile
        env:
          JAVA_VERSION: (8 11 17)
          # MCDR_VERSION: 2
        run: /usr/bin/env bash generater.sh
      -
        name: Build & Publish Docker images
        env:
          PUBLIC_PREFIX: ${{ secrets.DOCKERHUB_USERNAME }}/minecraft
          ASYNC_BUILD: true
        run: /usr/bin/env bash publish.sh
